/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) SDK makes it easy to predict customer behavior using a simple API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Persona,
    PersonaFromJSON,
    PersonaFromJSONTyped,
    PersonaToJSON,
} from './Persona';
import {
    ResourceStatus,
    ResourceStatusFromJSON,
    ResourceStatusFromJSONTyped,
    ResourceStatusToJSON,
} from './ResourceStatus';

/**
 * A set of customer personas.
 * @export
 * @interface PersonaSet
 */
export interface PersonaSet {
    /**
     * 
     * @type {string}
     * @memberof PersonaSet
     */
    cohortId: string;
    /**
     * When this resource was created.
     * @type {Date}
     * @memberof PersonaSet
     */
    createdAt: Date;
    /**
     * A unique ID for this resource.
     * @type {string}
     * @memberof PersonaSet
     */
    id: string;
    /**
     * The personas that belong to this persona set
     * @type {Array<Persona>}
     * @memberof PersonaSet
     */
    personas?: Array<Persona>;
    /**
     * The type of this resource.
     * @type {string}
     * @memberof PersonaSet
     */
    resourceType: string;
    /**
     * 
     * @type {ResourceStatus}
     * @memberof PersonaSet
     */
    status: ResourceStatus;
    /**
     * When the status of this resource was last updated.
     * @type {Date}
     * @memberof PersonaSet
     */
    statusChangedAt?: Date;
    /**
     * If this resource has `status == "error"`, this will contain an error message.
     * @type {string}
     * @memberof PersonaSet
     */
    statusError?: string;
    /**
     * When this resource was last updated.
     * @type {Date}
     * @memberof PersonaSet
     */
    updatedAt: Date;
}

export function PersonaSetFromJSON(json: any): PersonaSet {
    return PersonaSetFromJSONTyped(json, false);
}

export function PersonaSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonaSet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cohortId': json['cohort_id'],
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'personas': !exists(json, 'personas') ? undefined : ((json['personas'] as Array<any>).map(PersonaFromJSON)),
        'resourceType': json['resource_type'],
        'status': ResourceStatusFromJSON(json['status']),
        'statusChangedAt': !exists(json, 'status_changed_at') ? undefined : (new Date(json['status_changed_at'])),
        'statusError': !exists(json, 'status_error') ? undefined : json['status_error'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function PersonaSetToJSON(value?: PersonaSet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cohort_id': value.cohortId,
        'created_at': (value.createdAt.toISOString()),
        'id': value.id,
        'personas': value.personas === undefined ? undefined : ((value.personas as Array<any>).map(PersonaToJSON)),
        'resource_type': value.resourceType,
        'status': ResourceStatusToJSON(value.status),
        'status_changed_at': value.statusChangedAt === undefined ? undefined : (value.statusChangedAt.toISOString()),
        'status_error': value.statusError,
        'updated_at': (value.updatedAt.toISOString()),
    };
}

