/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalysisDimensionsTraitBinBoolean
 */
export interface AnalysisDimensionsTraitBinBoolean {
    /**
     * The numeric total of individuals found by this status.
     * @type {number}
     * @memberof AnalysisDimensionsTraitBinBoolean
     */
    count: number;
    /**
     * Nominal dimensions are represented as a list of bins, where each bin is a boolean or no value (to represent null) and a resulting count that is the individuals found that match that value.
     * @type {string}
     * @memberof AnalysisDimensionsTraitBinBoolean
     */
    data_type: string;
    /**
     * The count represented as a percentage based on the sum of counts.
     * @type {number}
     * @memberof AnalysisDimensionsTraitBinBoolean
     */
    percent: number;
    /**
     * The status used to count individuals by. No value means an invidiual with neither true or false value i.e. null.
     * @type {boolean}
     * @memberof AnalysisDimensionsTraitBinBoolean
     */
    value?: boolean;
}

export function AnalysisDimensionsTraitBinBooleanFromJSON(json: any): AnalysisDimensionsTraitBinBoolean {
    return AnalysisDimensionsTraitBinBooleanFromJSONTyped(json, false);
}

export function AnalysisDimensionsTraitBinBooleanFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalysisDimensionsTraitBinBoolean {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'data_type': json['data_type'],
        'percent': json['percent'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function AnalysisDimensionsTraitBinBooleanToJSON(value?: AnalysisDimensionsTraitBinBoolean | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'data_type': value.data_type,
        'percent': value.percent,
        'value': value.value,
    };
}

