/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AnalysisFeatureDirectionalityBoolean,
    AnalysisFeatureDirectionalityBooleanFromJSON,
    AnalysisFeatureDirectionalityBooleanFromJSONTyped,
    AnalysisFeatureDirectionalityBooleanToJSON,
} from './AnalysisFeatureDirectionalityBoolean';
import {
    AnalysisFeatureDirectionalityDate,
    AnalysisFeatureDirectionalityDateFromJSON,
    AnalysisFeatureDirectionalityDateFromJSONTyped,
    AnalysisFeatureDirectionalityDateToJSON,
} from './AnalysisFeatureDirectionalityDate';
import {
    AnalysisFeatureDirectionalityNumber,
    AnalysisFeatureDirectionalityNumberFromJSON,
    AnalysisFeatureDirectionalityNumberFromJSONTyped,
    AnalysisFeatureDirectionalityNumberToJSON,
} from './AnalysisFeatureDirectionalityNumber';
import {
    AnalysisFeatureDirectionalityText,
    AnalysisFeatureDirectionalityTextFromJSON,
    AnalysisFeatureDirectionalityTextFromJSONTyped,
    AnalysisFeatureDirectionalityTextToJSON,
} from './AnalysisFeatureDirectionalityText';

/**
 * @type AnalysisFeatureDirectionality
 * 
 * @export
 */
export type AnalysisFeatureDirectionality = { data_type: 'boolean' } & AnalysisFeatureDirectionalityBoolean | { data_type: 'date' } & AnalysisFeatureDirectionalityDate | { data_type: 'number' } & AnalysisFeatureDirectionalityNumber | { data_type: 'text' } & AnalysisFeatureDirectionalityText;

export function AnalysisFeatureDirectionalityFromJSON(json: any): AnalysisFeatureDirectionality {
    return AnalysisFeatureDirectionalityFromJSONTyped(json, false);
}

export function AnalysisFeatureDirectionalityFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalysisFeatureDirectionality {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['data_type']) {
        case 'boolean':
            return {...AnalysisFeatureDirectionalityBooleanFromJSONTyped(json, true), data_type: 'boolean'};
        case 'date':
            return {...AnalysisFeatureDirectionalityDateFromJSONTyped(json, true), data_type: 'date'};
        case 'number':
            return {...AnalysisFeatureDirectionalityNumberFromJSONTyped(json, true), data_type: 'number'};
        case 'text':
            return {...AnalysisFeatureDirectionalityTextFromJSONTyped(json, true), data_type: 'text'};
        default:
            throw new Error(`No variant of AnalysisFeatureDirectionality exists with 'data_type=${json['data_type']}'`);
    }
}

export function AnalysisFeatureDirectionalityToJSON(value?: AnalysisFeatureDirectionality | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['data_type']) {
        case 'boolean':
            return AnalysisFeatureDirectionalityBooleanToJSON(value);
        case 'date':
            return AnalysisFeatureDirectionalityDateToJSON(value);
        case 'number':
            return AnalysisFeatureDirectionalityNumberToJSON(value);
        case 'text':
            return AnalysisFeatureDirectionalityTextToJSON(value);
        default:
            throw new Error(`No variant of AnalysisFeatureDirectionality exists with 'data_type=${value['data_type']}'`);
    }
}

