/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (Parameters used to POST a new value of the `ConnectionOptionsGcpGcsCsv` type.)
 * 
 * GCS connection options
 * @export
 * @interface ConnectionOptionsGcpGcsCsvPost
 */
export interface ConnectionOptionsGcpGcsCsvPost {
    /**
     * Bucket name
     * @type {string}
     * @memberof ConnectionOptionsGcpGcsCsvPost
     */
    bucket_name: string;
    /**
     * Project ID
     * @type {string}
     * @memberof ConnectionOptionsGcpGcsCsvPost
     */
    project_id: string;
    /**
     * The type of connection
     * @type {string}
     * @memberof ConnectionOptionsGcpGcsCsvPost
     */
    type: string;
}

export function ConnectionOptionsGcpGcsCsvPostFromJSON(json: any): ConnectionOptionsGcpGcsCsvPost {
    return ConnectionOptionsGcpGcsCsvPostFromJSONTyped(json, false);
}

export function ConnectionOptionsGcpGcsCsvPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionOptionsGcpGcsCsvPost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bucket_name': json['bucket_name'],
        'project_id': json['project_id'],
        'type': json['type'],
    };
}

export function ConnectionOptionsGcpGcsCsvPostToJSON(value?: ConnectionOptionsGcpGcsCsvPost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bucket_name': value.bucket_name,
        'project_id': value.project_id,
        'type': value.type,
    };
}

