/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (Parameters used to POST a new value of the `ConnectionOptionsTiktok` type.)
 * 
 * TikTok connection options
 * @export
 * @interface ConnectionOptionsTiktokPost
 */
export interface ConnectionOptionsTiktokPost {
    /**
     * Account id for the TikTok connection
     * @type {string}
     * @memberof ConnectionOptionsTiktokPost
     */
    tiktok_account_id?: string;
    /**
     * The type of connection
     * @type {string}
     * @memberof ConnectionOptionsTiktokPost
     */
    type: string;
}

export function ConnectionOptionsTiktokPostFromJSON(json: any): ConnectionOptionsTiktokPost {
    return ConnectionOptionsTiktokPostFromJSONTyped(json, false);
}

export function ConnectionOptionsTiktokPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionOptionsTiktokPost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tiktok_account_id': !exists(json, 'tiktok_account_id') ? undefined : json['tiktok_account_id'],
        'type': json['type'],
    };
}

export function ConnectionOptionsTiktokPostToJSON(value?: ConnectionOptionsTiktokPost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tiktok_account_id': value.tiktok_account_id,
        'type': value.type,
    };
}

