/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (Parameters used to POST a new value of the `ConnectionOptionsGoogleAds` type.)
 * 
 * Google Ads connection options
 * @export
 * @interface ConnectionOptionsGoogleAdsPost
 */
export interface ConnectionOptionsGoogleAdsPost {
    /**
     * Customer ID for the Google Ads connection
     * @type {string}
     * @memberof ConnectionOptionsGoogleAdsPost
     */
    customer_id?: string;
    /**
     * Password for the Google Ads connection
     * @type {string}
     * @memberof ConnectionOptionsGoogleAdsPost
     */
    password?: string;
    /**
     * The type of connection
     * @type {string}
     * @memberof ConnectionOptionsGoogleAdsPost
     */
    type: string;
    /**
     * Username for the Google Ads connection
     * @type {string}
     * @memberof ConnectionOptionsGoogleAdsPost
     */
    username?: string;
}

export function ConnectionOptionsGoogleAdsPostFromJSON(json: any): ConnectionOptionsGoogleAdsPost {
    return ConnectionOptionsGoogleAdsPostFromJSONTyped(json, false);
}

export function ConnectionOptionsGoogleAdsPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionOptionsGoogleAdsPost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customer_id': !exists(json, 'customer_id') ? undefined : json['customer_id'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'type': json['type'],
        'username': !exists(json, 'username') ? undefined : json['username'],
    };
}

export function ConnectionOptionsGoogleAdsPostToJSON(value?: ConnectionOptionsGoogleAdsPost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customer_id': value.customer_id,
        'password': value.password,
        'type': value.type,
        'username': value.username,
    };
}

