/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) SDK makes it easy to predict customer behavior using a simple API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ConnectionOptionsAzureSqlServerMergePatch,
    ConnectionOptionsAzureSqlServerMergePatchFromJSON,
    ConnectionOptionsAzureSqlServerMergePatchFromJSONTyped,
    ConnectionOptionsAzureSqlServerMergePatchToJSON,
} from './ConnectionOptionsAzureSqlServerMergePatch';
import {
    ConnectionOptionsBigQueryMergePatch,
    ConnectionOptionsBigQueryMergePatchFromJSON,
    ConnectionOptionsBigQueryMergePatchFromJSONTyped,
    ConnectionOptionsBigQueryMergePatchToJSON,
} from './ConnectionOptionsBigQueryMergePatch';
import {
    ConnectionOptionsClassicMergePatch,
    ConnectionOptionsClassicMergePatchFromJSON,
    ConnectionOptionsClassicMergePatchFromJSONTyped,
    ConnectionOptionsClassicMergePatchToJSON,
} from './ConnectionOptionsClassicMergePatch';
import {
    ConnectionOptionsRedshiftMergePatch,
    ConnectionOptionsRedshiftMergePatchFromJSON,
    ConnectionOptionsRedshiftMergePatchFromJSONTyped,
    ConnectionOptionsRedshiftMergePatchToJSON,
} from './ConnectionOptionsRedshiftMergePatch';
import {
    ConnectionOptionsS3CsvMergePatch,
    ConnectionOptionsS3CsvMergePatchFromJSON,
    ConnectionOptionsS3CsvMergePatchFromJSONTyped,
    ConnectionOptionsS3CsvMergePatchToJSON,
} from './ConnectionOptionsS3CsvMergePatch';
import {
    ConnectionOptionsSnowflakeMergePatch,
    ConnectionOptionsSnowflakeMergePatchFromJSON,
    ConnectionOptionsSnowflakeMergePatchFromJSONTyped,
    ConnectionOptionsSnowflakeMergePatchToJSON,
} from './ConnectionOptionsSnowflakeMergePatch';

/**
 * @type ConnectionOptionsMergePatch
 * The connection-specific options. These vary by connection type.
 * @export
 */
export type ConnectionOptionsMergePatch = { type: 'azure_sql_server' } & ConnectionOptionsAzureSqlServerMergePatch | { type: 'bigquery' } & ConnectionOptionsBigQueryMergePatch | { type: 'classic' } & ConnectionOptionsClassicMergePatch | { type: 'redshift' } & ConnectionOptionsRedshiftMergePatch | { type: 's3_csv' } & ConnectionOptionsS3CsvMergePatch | { type: 'snowflake' } & ConnectionOptionsSnowflakeMergePatch;

export function ConnectionOptionsMergePatchFromJSON(json: any): ConnectionOptionsMergePatch {
    return ConnectionOptionsMergePatchFromJSONTyped(json, false);
}

export function ConnectionOptionsMergePatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionOptionsMergePatch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['type']) {
        case 'azure_sql_server':
            return {...ConnectionOptionsAzureSqlServerMergePatchFromJSONTyped(json, true), type: 'azure_sql_server'};
        case 'bigquery':
            return {...ConnectionOptionsBigQueryMergePatchFromJSONTyped(json, true), type: 'bigquery'};
        case 'classic':
            return {...ConnectionOptionsClassicMergePatchFromJSONTyped(json, true), type: 'classic'};
        case 'redshift':
            return {...ConnectionOptionsRedshiftMergePatchFromJSONTyped(json, true), type: 'redshift'};
        case 's3_csv':
            return {...ConnectionOptionsS3CsvMergePatchFromJSONTyped(json, true), type: 's3_csv'};
        case 'snowflake':
            return {...ConnectionOptionsSnowflakeMergePatchFromJSONTyped(json, true), type: 'snowflake'};
        default:
            throw new Error(`No variant of ConnectionOptionsMergePatch exists with 'type=${json['type']}'`);
    }
}

export function ConnectionOptionsMergePatchToJSON(value?: ConnectionOptionsMergePatch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['type']) {
        case 'azure_sql_server':
            return ConnectionOptionsAzureSqlServerMergePatchToJSON(value);
        case 'bigquery':
            return ConnectionOptionsBigQueryMergePatchToJSON(value);
        case 'classic':
            return ConnectionOptionsClassicMergePatchToJSON(value);
        case 'redshift':
            return ConnectionOptionsRedshiftMergePatchToJSON(value);
        case 's3_csv':
            return ConnectionOptionsS3CsvMergePatchToJSON(value);
        case 'snowflake':
            return ConnectionOptionsSnowflakeMergePatchToJSON(value);
        default:
            throw new Error(`No variant of ConnectionOptionsMergePatch exists with 'type=${value['type']}'`);
    }
}

