/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConnectionOptionsPut,
    ConnectionOptionsPutFromJSON,
    ConnectionOptionsPutFromJSONTyped,
    ConnectionOptionsPutToJSON,
} from './ConnectionOptionsPut';

/**
 * (Parameters used to PUT a value of the `Connection` type.)
 * 
 * Configuration for connecting data between Faraday and an external location.
 * 
 * Connections are required when working with **replication targets**.
 * @export
 * @interface ConnectionPut
 */
export interface ConnectionPut {
    /**
     * A user-friendly name of the connection.
     * @type {string}
     * @memberof ConnectionPut
     */
    name: string;
    /**
     * 
     * @type {ConnectionOptionsPut}
     * @memberof ConnectionPut
     */
    options: ConnectionOptionsPut;
}

export function ConnectionPutFromJSON(json: any): ConnectionPut {
    return ConnectionPutFromJSONTyped(json, false);
}

export function ConnectionPutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionPut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'options': ConnectionOptionsPutFromJSON(json['options']),
    };
}

export function ConnectionPutToJSON(value?: ConnectionPut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'options': ConnectionOptionsPutToJSON(value.options),
    };
}

