/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (Parameters used to PUT a value of the `ConnectionOptionsStripe` type.)
 * 
 * Stripe connection options
 * @export
 * @interface ConnectionOptionsStripePut
 */
export interface ConnectionOptionsStripePut {
    /**
     * Password for the Stripe connection
     * @type {string}
     * @memberof ConnectionOptionsStripePut
     */
    password?: string;
    /**
     * The type of connection
     * @type {string}
     * @memberof ConnectionOptionsStripePut
     */
    type: string;
    /**
     * Username for the Stripe connection
     * @type {string}
     * @memberof ConnectionOptionsStripePut
     */
    username?: string;
}

export function ConnectionOptionsStripePutFromJSON(json: any): ConnectionOptionsStripePut {
    return ConnectionOptionsStripePutFromJSONTyped(json, false);
}

export function ConnectionOptionsStripePutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionOptionsStripePut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'password': !exists(json, 'password') ? undefined : json['password'],
        'type': json['type'],
        'username': !exists(json, 'username') ? undefined : json['username'],
    };
}

export function ConnectionOptionsStripePutToJSON(value?: ConnectionOptionsStripePut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'password': value.password,
        'type': value.type,
        'username': value.username,
    };
}

