/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (Parameters used to PATCH the `ConnectionOptionsLinkedinAds` type.)
 * 
 * LinkedIn Ads connection options
 * @export
 * @interface ConnectionOptionsLinkedinAdsMergePatch
 */
export interface ConnectionOptionsLinkedinAdsMergePatch {
    /**
     * Password for the LinkedIn Ads connection
     * @type {string}
     * @memberof ConnectionOptionsLinkedinAdsMergePatch
     */
    password?: string | null;
    /**
     * The type of connection
     * @type {string}
     * @memberof ConnectionOptionsLinkedinAdsMergePatch
     */
    type: string;
    /**
     * Username for the LinkedIn Ads connection
     * @type {string}
     * @memberof ConnectionOptionsLinkedinAdsMergePatch
     */
    username?: string | null;
}

export function ConnectionOptionsLinkedinAdsMergePatchFromJSON(json: any): ConnectionOptionsLinkedinAdsMergePatch {
    return ConnectionOptionsLinkedinAdsMergePatchFromJSONTyped(json, false);
}

export function ConnectionOptionsLinkedinAdsMergePatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionOptionsLinkedinAdsMergePatch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'password': !exists(json, 'password') ? undefined : json['password'],
        'type': json['type'],
        'username': !exists(json, 'username') ? undefined : json['username'],
    };
}

export function ConnectionOptionsLinkedinAdsMergePatchToJSON(value?: ConnectionOptionsLinkedinAdsMergePatch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'password': value.password,
        'type': value.type,
        'username': value.username,
    };
}

