/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) SDK makes it easy to predict customer behavior using a simple API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IdentitySetsPost,
    IdentitySetsPostFromJSON,
    IdentitySetsPostFromJSONTyped,
    IdentitySetsPostToJSON,
} from './IdentitySetsPost';
import {
    OutputToStreamsPost,
    OutputToStreamsPostFromJSON,
    OutputToStreamsPostFromJSONTyped,
    OutputToStreamsPostToJSON,
} from './OutputToStreamsPost';

/**
 * 
 * @export
 * @interface DatasetPost
 */
export interface DatasetPost {
    /**
     * 
     * @type {IdentitySetsPost}
     * @memberof DatasetPost
     */
    identity_sets: IdentitySetsPost;
    /**
     * A column specifying a date associated with a record. After each
     * ingestion, the most recent value from `incremental_column` on any
     * record will be recorded, and during future ingestions, any
     * records with a value older than `incremental_column` will be ignored.
     * 
     * Cannot currently be used with `upsert_columns`. Prefer
     * `upsert_columns` when possible.
     * @type {string}
     * @memberof DatasetPost
     */
    incremental_column?: string;
    /**
     * 
     * @type {OutputToStreamsPost}
     * @memberof DatasetPost
     */
    output_to_streams: OutputToStreamsPost;
    /**
     * 
     * @type {string}
     * @memberof DatasetPost
     */
    upload_directory: string;
    /**
     * A column or set of columns that uniquely identify an input row. If
     * multiple rows are ingested with identical values in the columns
     * specified by `upsert_columns`, the newest will be used.
     * 
     * Cannot currently be used with `incremental_column`.
     * 
     * If neither `upsert_columns` nor `incremental_column` are
     * specified, each unique row will be ingested once.
     * @type {Array<string>}
     * @memberof DatasetPost
     */
    upsert_columns?: Array<string>;
}

export function DatasetPostFromJSON(json: any): DatasetPost {
    return DatasetPostFromJSONTyped(json, false);
}

export function DatasetPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetPost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'identity_sets': IdentitySetsPostFromJSON(json['identity_sets']),
        'incremental_column': !exists(json, 'incremental_column') ? undefined : json['incremental_column'],
        'output_to_streams': OutputToStreamsPostFromJSON(json['output_to_streams']),
        'upload_directory': json['upload_directory'],
        'upsert_columns': !exists(json, 'upsert_columns') ? undefined : json['upsert_columns'],
    };
}

export function DatasetPostToJSON(value?: DatasetPost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'identity_sets': IdentitySetsPostToJSON(value.identity_sets),
        'incremental_column': value.incremental_column,
        'output_to_streams': OutputToStreamsPostToJSON(value.output_to_streams),
        'upload_directory': value.upload_directory,
        'upsert_columns': value.upsert_columns,
    };
}

