/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (Parameters used to PUT a value of the `DatasetOptionsShopify` type.)
 * 
 * Shopify dataset options
 * @export
 * @interface DatasetOptionsShopifyPut
 */
export interface DatasetOptionsShopifyPut {
    /**
     * The type of connection
     * @type {string}
     * @memberof DatasetOptionsShopifyPut
     */
    type: string;
}

export function DatasetOptionsShopifyPutFromJSON(json: any): DatasetOptionsShopifyPut {
    return DatasetOptionsShopifyPutFromJSONTyped(json, false);
}

export function DatasetOptionsShopifyPutFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetOptionsShopifyPut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function DatasetOptionsShopifyPutToJSON(value?: DatasetOptionsShopifyPut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
    };
}

