/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) SDK makes it easy to predict customer behavior using a simple API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    DatasetOptionsBigQueryPut,
    DatasetOptionsBigQueryPutFromJSON,
    DatasetOptionsBigQueryPutFromJSONTyped,
    DatasetOptionsBigQueryPutToJSON,
} from './DatasetOptionsBigQueryPut';
import {
    DatasetOptionsClassicPut,
    DatasetOptionsClassicPutFromJSON,
    DatasetOptionsClassicPutFromJSONTyped,
    DatasetOptionsClassicPutToJSON,
} from './DatasetOptionsClassicPut';
import {
    DatasetOptionsHostedCsvPut,
    DatasetOptionsHostedCsvPutFromJSON,
    DatasetOptionsHostedCsvPutFromJSONTyped,
    DatasetOptionsHostedCsvPutToJSON,
} from './DatasetOptionsHostedCsvPut';
import {
    DatasetOptionsSnowflakePut,
    DatasetOptionsSnowflakePutFromJSON,
    DatasetOptionsSnowflakePutFromJSONTyped,
    DatasetOptionsSnowflakePutToJSON,
} from './DatasetOptionsSnowflakePut';

/**
 * @type DatasetOptionsPut
 * Dataset connection options
 * @export
 */
export type DatasetOptionsPut = { type: 'bigquery' } & DatasetOptionsBigQueryPut | { type: 'classic' } & DatasetOptionsClassicPut | { type: 'hosted_csv' } & DatasetOptionsHostedCsvPut | { type: 'snowflake' } & DatasetOptionsSnowflakePut;

export function DatasetOptionsPutFromJSON(json: any): DatasetOptionsPut {
    return DatasetOptionsPutFromJSONTyped(json, false);
}

export function DatasetOptionsPutFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetOptionsPut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['type']) {
        case 'bigquery':
            return {...DatasetOptionsBigQueryPutFromJSONTyped(json, true), type: 'bigquery'};
        case 'classic':
            return {...DatasetOptionsClassicPutFromJSONTyped(json, true), type: 'classic'};
        case 'hosted_csv':
            return {...DatasetOptionsHostedCsvPutFromJSONTyped(json, true), type: 'hosted_csv'};
        case 'snowflake':
            return {...DatasetOptionsSnowflakePutFromJSONTyped(json, true), type: 'snowflake'};
        default:
            throw new Error(`No variant of DatasetOptionsPut exists with 'type=${json['type']}'`);
    }
}

export function DatasetOptionsPutToJSON(value?: DatasetOptionsPut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['type']) {
        case 'bigquery':
            return DatasetOptionsBigQueryPutToJSON(value);
        case 'classic':
            return DatasetOptionsClassicPutToJSON(value);
        case 'hosted_csv':
            return DatasetOptionsHostedCsvPutToJSON(value);
        case 'snowflake':
            return DatasetOptionsSnowflakePutToJSON(value);
        default:
            throw new Error(`No variant of DatasetOptionsPut exists with 'type=${value['type']}'`);
    }
}

