/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (Parameters used to PUT a value of the `DatasetOptionsSnowflake` type.)
 * 
 * Snowflake dataset options
 * @export
 * @interface DatasetOptionsSnowflakePut
 */
export interface DatasetOptionsSnowflakePut {
    /**
     * If the table was created with case sensitive columns, this setting may be required.
     * @type {boolean}
     * @memberof DatasetOptionsSnowflakePut
     */
    case_sensitive_columns?: boolean;
    /**
     * Table name
     * @type {string}
     * @memberof DatasetOptionsSnowflakePut
     */
    table_name: string;
    /**
     * The type of connection
     * @type {string}
     * @memberof DatasetOptionsSnowflakePut
     */
    type: string;
}

export function DatasetOptionsSnowflakePutFromJSON(json: any): DatasetOptionsSnowflakePut {
    return DatasetOptionsSnowflakePutFromJSONTyped(json, false);
}

export function DatasetOptionsSnowflakePutFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetOptionsSnowflakePut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'case_sensitive_columns': !exists(json, 'case_sensitive_columns') ? undefined : json['case_sensitive_columns'],
        'table_name': json['table_name'],
        'type': json['type'],
    };
}

export function DatasetOptionsSnowflakePutToJSON(value?: DatasetOptionsSnowflakePut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'case_sensitive_columns': value.case_sensitive_columns,
        'table_name': value.table_name,
        'type': value.type,
    };
}

