/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DatasetOptionsMergePatch,
    DatasetOptionsMergePatchFromJSON,
    DatasetOptionsMergePatchFromJSONTyped,
    DatasetOptionsMergePatchToJSON,
} from './DatasetOptionsMergePatch';
import {
    IdentitySetsMergePatch,
    IdentitySetsMergePatchFromJSON,
    IdentitySetsMergePatchFromJSONTyped,
    IdentitySetsMergePatchToJSON,
} from './IdentitySetsMergePatch';
import {
    OutputToStreamsMergePatch,
    OutputToStreamsMergePatchFromJSON,
    OutputToStreamsMergePatchFromJSONTyped,
    OutputToStreamsMergePatchToJSON,
} from './OutputToStreamsMergePatch';
import {
    OutputToTraitsMergePatch,
    OutputToTraitsMergePatchFromJSON,
    OutputToTraitsMergePatchFromJSONTyped,
    OutputToTraitsMergePatchToJSON,
} from './OutputToTraitsMergePatch';

/**
 * (Parameters used to PATCH the `Dataset` type.)
 * 
 * Tabular data describing orders, customers, leads, etc.
 * @export
 * @interface DatasetMergePatch
 */
export interface DatasetMergePatch {
    /**
     * 
     * @type {IdentitySetsMergePatch}
     * @memberof DatasetMergePatch
     */
    identity_sets?: IdentitySetsMergePatch;
    /**
     * An identifying name for this dataset.
     * @type {string}
     * @memberof DatasetMergePatch
     */
    name?: string;
    /**
     * 
     * @type {DatasetOptionsMergePatch}
     * @memberof DatasetMergePatch
     */
    options?: DatasetOptionsMergePatch;
    /**
     * 
     * @type {OutputToStreamsMergePatch}
     * @memberof DatasetMergePatch
     */
    output_to_streams?: OutputToStreamsMergePatch | null;
    /**
     * 
     * @type {OutputToTraitsMergePatch}
     * @memberof DatasetMergePatch
     */
    output_to_traits?: OutputToTraitsMergePatch | null;
    /**
     * A dataset in preview mode will only detect columns and produce a data preview, but not ingest the data.
     * 
     * Defaults to undefined, which is equivalent to false.
     * @type {boolean}
     * @memberof DatasetMergePatch
     */
    preview?: boolean | null;
    /**
     * The name of the column that references an ID from an external system.
     * 
     * Setting this enables export of data via <a href="/reference/createtarget">`/targets`</a> that is keyed on this field.
     * @type {string}
     * @memberof DatasetMergePatch
     */
    reference_key_column?: string | null;
    /**
     * A column or set of columns that uniquely identify an input row. If
     * multiple rows are ingested with identical values in the columns
     * specified by `upsert_columns`, the newest will be used.
     * 
     * Cannot currently be used with `incremental_column`.
     * 
     * If neither `upsert_columns` nor `incremental_column` are
     * specified, each unique row will be ingested once.
     * @type {Array<string>}
     * @memberof DatasetMergePatch
     */
    upsert_columns?: Array<string> | null;
}

export function DatasetMergePatchFromJSON(json: any): DatasetMergePatch {
    return DatasetMergePatchFromJSONTyped(json, false);
}

export function DatasetMergePatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetMergePatch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'identity_sets': !exists(json, 'identity_sets') ? undefined : IdentitySetsMergePatchFromJSON(json['identity_sets']),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'options': !exists(json, 'options') ? undefined : DatasetOptionsMergePatchFromJSON(json['options']),
        'output_to_streams': !exists(json, 'output_to_streams') ? undefined : OutputToStreamsMergePatchFromJSON(json['output_to_streams']),
        'output_to_traits': !exists(json, 'output_to_traits') ? undefined : OutputToTraitsMergePatchFromJSON(json['output_to_traits']),
        'preview': !exists(json, 'preview') ? undefined : json['preview'],
        'reference_key_column': !exists(json, 'reference_key_column') ? undefined : json['reference_key_column'],
        'upsert_columns': !exists(json, 'upsert_columns') ? undefined : json['upsert_columns'],
    };
}

export function DatasetMergePatchToJSON(value?: DatasetMergePatch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'identity_sets': IdentitySetsMergePatchToJSON(value.identity_sets),
        'name': value.name,
        'options': DatasetOptionsMergePatchToJSON(value.options),
        'output_to_streams': OutputToStreamsMergePatchToJSON(value.output_to_streams),
        'output_to_traits': OutputToTraitsMergePatchToJSON(value.output_to_traits),
        'preview': value.preview,
        'reference_key_column': value.reference_key_column,
        'upsert_columns': value.upsert_columns,
    };
}

