/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (Parameters used to PATCH the `DatasetOptionsRecharge` type.)
 * 
 * Recharge dataset options
 * @export
 * @interface DatasetOptionsRechargeMergePatch
 */
export interface DatasetOptionsRechargeMergePatch {
    /**
     * The type of connection
     * @type {string}
     * @memberof DatasetOptionsRechargeMergePatch
     */
    type: string;
}

export function DatasetOptionsRechargeMergePatchFromJSON(json: any): DatasetOptionsRechargeMergePatch {
    return DatasetOptionsRechargeMergePatchFromJSONTyped(json, false);
}

export function DatasetOptionsRechargeMergePatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetOptionsRechargeMergePatch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function DatasetOptionsRechargeMergePatchToJSON(value?: DatasetOptionsRechargeMergePatch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
    };
}

