/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DataMapColumnPut,
    DataMapColumnPutFromJSON,
    DataMapColumnPutFromJSONTyped,
    DataMapColumnPutToJSON,
} from './DataMapColumnPut';

/**
 * (Parameters used to PUT a value of the `DataMap` type.)
 * 
 * A mapping from dataset columns to what they mean. It is recommended to include a "datetime" column if possible, as it will improve the accuracy of models.
 * @export
 * @interface DataMapPut
 */
export interface DataMapPut {
    [key: string]: DataMapColumnPut | any;
    /**
     * 
     * @type {DataMapColumnPut}
     * @memberof DataMapPut
     */
    datetime?: DataMapColumnPut;
}

export function DataMapPutFromJSON(json: any): DataMapPut {
    return DataMapPutFromJSONTyped(json, false);
}

export function DataMapPutFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataMapPut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'datetime': !exists(json, 'datetime') ? undefined : DataMapColumnPutFromJSON(json['datetime']),
    };
}

export function DataMapPutToJSON(value?: DataMapPut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'datetime': DataMapColumnPutToJSON(value.datetime),
    };
}

