/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * RDS (SQL Server) dataset options
 * @export
 * @interface DatasetOptionsAwsRdsSqlServer
 */
export interface DatasetOptionsAwsRdsSqlServer {
    /**
     * Table name
     * @type {string}
     * @memberof DatasetOptionsAwsRdsSqlServer
     */
    table_name: string;
    /**
     * The type of connection
     * @type {string}
     * @memberof DatasetOptionsAwsRdsSqlServer
     */
    type: string;
}

export function DatasetOptionsAwsRdsSqlServerFromJSON(json: any): DatasetOptionsAwsRdsSqlServer {
    return DatasetOptionsAwsRdsSqlServerFromJSONTyped(json, false);
}

export function DatasetOptionsAwsRdsSqlServerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetOptionsAwsRdsSqlServer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'table_name': json['table_name'],
        'type': json['type'],
    };
}

export function DatasetOptionsAwsRdsSqlServerToJSON(value?: DatasetOptionsAwsRdsSqlServer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'table_name': value.table_name,
        'type': value.type,
    };
}

