/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DatasetOptionsPut,
    DatasetOptionsPutFromJSON,
    DatasetOptionsPutFromJSONTyped,
    DatasetOptionsPutToJSON,
} from './DatasetOptionsPut';
import {
    DatasetOutputAllColumnsAsTraits,
    DatasetOutputAllColumnsAsTraitsFromJSON,
    DatasetOutputAllColumnsAsTraitsFromJSONTyped,
    DatasetOutputAllColumnsAsTraitsToJSON,
} from './DatasetOutputAllColumnsAsTraits';
import {
    IdentitySetsPut,
    IdentitySetsPutFromJSON,
    IdentitySetsPutFromJSONTyped,
    IdentitySetsPutToJSON,
} from './IdentitySetsPut';
import {
    OutputToStreamsPut,
    OutputToStreamsPutFromJSON,
    OutputToStreamsPutFromJSONTyped,
    OutputToStreamsPutToJSON,
} from './OutputToStreamsPut';
import {
    OutputToTraitsPut,
    OutputToTraitsPutFromJSON,
    OutputToTraitsPutFromJSONTyped,
    OutputToTraitsPutToJSON,
} from './OutputToTraitsPut';

/**
 * (Parameters used to PUT a value of the `Dataset` type.)
 * 
 * Tabular data describing orders, customers, leads, etc.
 * @export
 * @interface DatasetPut
 */
export interface DatasetPut {
    /**
     * 
     * @type {IdentitySetsPut}
     * @memberof DatasetPut
     */
    identity_sets: IdentitySetsPut;
    /**
     * An identifying name for this dataset.
     * @type {string}
     * @memberof DatasetPut
     */
    name: string;
    /**
     * 
     * @type {DatasetOptionsPut}
     * @memberof DatasetPut
     */
    options: DatasetOptionsPut;
    /**
     * 
     * @type {DatasetOutputAllColumnsAsTraits}
     * @memberof DatasetPut
     */
    output_all_columns_as_traits?: DatasetOutputAllColumnsAsTraits;
    /**
     * 
     * @type {OutputToStreamsPut}
     * @memberof DatasetPut
     */
    output_to_streams?: OutputToStreamsPut;
    /**
     * 
     * @type {OutputToTraitsPut}
     * @memberof DatasetPut
     */
    output_to_traits?: OutputToTraitsPut;
    /**
     * A dataset in preview mode will only detect columns and produce a data preview, but not ingest the data.
     * 
     * Defaults to undefined, which is equivalent to false.
     * @type {boolean}
     * @memberof DatasetPut
     */
    preview?: boolean;
    /**
     * Currently supported:
     *   - 'suppress' - data can be used for modeling but will be excluded from pipelines and deployments (do not contact)
     *   - 'delete' - data can not be used for modeling and will be excluded from pipelines and deployments (delete and do not contact)
     * @type {string}
     * @memberof DatasetPut
     */
    privacy?: DatasetPutPrivacyEnum;
    /**
     * **Deprecated:** use reference_key_columns instead
     * The name of the column that references an ID from an external system.
     * 
     * Setting this enables export of data via <a href="/reference/createtarget">`/targets`</a> that is keyed on this field.
     * @type {string}
     * @memberof DatasetPut
     */
    reference_key_column?: string;
    /**
     * The names of columns that reference IDs from an external system.
     * 
     * Setting this enables export of data via <a href="/reference/createtarget">`/targets`</a> that is keyed on this field.
     * @type {Array<string>}
     * @memberof DatasetPut
     */
    reference_key_columns?: Array<string>;
    /**
     * A column or set of columns that uniquely identify an input row. If
     * multiple rows are ingested with identical values in the columns
     * specified by `upsert_columns`, the newest will be used.
     * 
     * Cannot currently be used with `incremental_column`.
     * 
     * If neither `upsert_columns` nor `incremental_column` are
     * specified, each unique row will be ingested once.
     * @type {Array<string>}
     * @memberof DatasetPut
     */
    upsert_columns?: Array<string>;
}

/**
* @export
* @enum {string}
*/
export enum DatasetPutPrivacyEnum {
    Suppress = 'suppress',
    Delete = 'delete'
}

export function DatasetPutFromJSON(json: any): DatasetPut {
    return DatasetPutFromJSONTyped(json, false);
}

export function DatasetPutFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetPut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'identity_sets': IdentitySetsPutFromJSON(json['identity_sets']),
        'name': json['name'],
        'options': DatasetOptionsPutFromJSON(json['options']),
        'output_all_columns_as_traits': !exists(json, 'output_all_columns_as_traits') ? undefined : DatasetOutputAllColumnsAsTraitsFromJSON(json['output_all_columns_as_traits']),
        'output_to_streams': !exists(json, 'output_to_streams') ? undefined : OutputToStreamsPutFromJSON(json['output_to_streams']),
        'output_to_traits': !exists(json, 'output_to_traits') ? undefined : OutputToTraitsPutFromJSON(json['output_to_traits']),
        'preview': !exists(json, 'preview') ? undefined : json['preview'],
        'privacy': !exists(json, 'privacy') ? undefined : json['privacy'],
        'reference_key_column': !exists(json, 'reference_key_column') ? undefined : json['reference_key_column'],
        'reference_key_columns': !exists(json, 'reference_key_columns') ? undefined : json['reference_key_columns'],
        'upsert_columns': !exists(json, 'upsert_columns') ? undefined : json['upsert_columns'],
    };
}

export function DatasetPutToJSON(value?: DatasetPut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'identity_sets': IdentitySetsPutToJSON(value.identity_sets),
        'name': value.name,
        'options': DatasetOptionsPutToJSON(value.options),
        'output_all_columns_as_traits': DatasetOutputAllColumnsAsTraitsToJSON(value.output_all_columns_as_traits),
        'output_to_streams': OutputToStreamsPutToJSON(value.output_to_streams),
        'output_to_traits': OutputToTraitsPutToJSON(value.output_to_traits),
        'preview': value.preview,
        'privacy': value.privacy,
        'reference_key_column': value.reference_key_column,
        'reference_key_columns': value.reference_key_columns,
        'upsert_columns': value.upsert_columns,
    };
}

