/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    DatasetOptionsAwsAuroraMysqlMergePatch,
    DatasetOptionsAwsAuroraMysqlMergePatchFromJSON,
    DatasetOptionsAwsAuroraMysqlMergePatchFromJSONTyped,
    DatasetOptionsAwsAuroraMysqlMergePatchToJSON,
} from './DatasetOptionsAwsAuroraMysqlMergePatch';
import {
    DatasetOptionsAwsAuroraPostgresMergePatch,
    DatasetOptionsAwsAuroraPostgresMergePatchFromJSON,
    DatasetOptionsAwsAuroraPostgresMergePatchFromJSONTyped,
    DatasetOptionsAwsAuroraPostgresMergePatchToJSON,
} from './DatasetOptionsAwsAuroraPostgresMergePatch';
import {
    DatasetOptionsAwsRdsMysqlMergePatch,
    DatasetOptionsAwsRdsMysqlMergePatchFromJSON,
    DatasetOptionsAwsRdsMysqlMergePatchFromJSONTyped,
    DatasetOptionsAwsRdsMysqlMergePatchToJSON,
} from './DatasetOptionsAwsRdsMysqlMergePatch';
import {
    DatasetOptionsAwsRdsPostgresMergePatch,
    DatasetOptionsAwsRdsPostgresMergePatchFromJSON,
    DatasetOptionsAwsRdsPostgresMergePatchFromJSONTyped,
    DatasetOptionsAwsRdsPostgresMergePatchToJSON,
} from './DatasetOptionsAwsRdsPostgresMergePatch';
import {
    DatasetOptionsAwsRdsSqlServerMergePatch,
    DatasetOptionsAwsRdsSqlServerMergePatchFromJSON,
    DatasetOptionsAwsRdsSqlServerMergePatchFromJSONTyped,
    DatasetOptionsAwsRdsSqlServerMergePatchToJSON,
} from './DatasetOptionsAwsRdsSqlServerMergePatch';
import {
    DatasetOptionsAwsRedshiftServerlessMergePatch,
    DatasetOptionsAwsRedshiftServerlessMergePatchFromJSON,
    DatasetOptionsAwsRedshiftServerlessMergePatchFromJSONTyped,
    DatasetOptionsAwsRedshiftServerlessMergePatchToJSON,
} from './DatasetOptionsAwsRedshiftServerlessMergePatch';
import {
    DatasetOptionsAzureSqlServerMergePatch,
    DatasetOptionsAzureSqlServerMergePatchFromJSON,
    DatasetOptionsAzureSqlServerMergePatchFromJSONTyped,
    DatasetOptionsAzureSqlServerMergePatchToJSON,
} from './DatasetOptionsAzureSqlServerMergePatch';
import {
    DatasetOptionsBigQueryMergePatch,
    DatasetOptionsBigQueryMergePatchFromJSON,
    DatasetOptionsBigQueryMergePatchFromJSONTyped,
    DatasetOptionsBigQueryMergePatchToJSON,
} from './DatasetOptionsBigQueryMergePatch';
import {
    DatasetOptionsClassicMergePatch,
    DatasetOptionsClassicMergePatchFromJSON,
    DatasetOptionsClassicMergePatchFromJSONTyped,
    DatasetOptionsClassicMergePatchToJSON,
} from './DatasetOptionsClassicMergePatch';
import {
    DatasetOptionsGcpCloudSqlMysqlMergePatch,
    DatasetOptionsGcpCloudSqlMysqlMergePatchFromJSON,
    DatasetOptionsGcpCloudSqlMysqlMergePatchFromJSONTyped,
    DatasetOptionsGcpCloudSqlMysqlMergePatchToJSON,
} from './DatasetOptionsGcpCloudSqlMysqlMergePatch';
import {
    DatasetOptionsGcpCloudSqlPostgresMergePatch,
    DatasetOptionsGcpCloudSqlPostgresMergePatchFromJSON,
    DatasetOptionsGcpCloudSqlPostgresMergePatchFromJSONTyped,
    DatasetOptionsGcpCloudSqlPostgresMergePatchToJSON,
} from './DatasetOptionsGcpCloudSqlPostgresMergePatch';
import {
    DatasetOptionsGcpCloudSqlSqlServerMergePatch,
    DatasetOptionsGcpCloudSqlSqlServerMergePatchFromJSON,
    DatasetOptionsGcpCloudSqlSqlServerMergePatchFromJSONTyped,
    DatasetOptionsGcpCloudSqlSqlServerMergePatchToJSON,
} from './DatasetOptionsGcpCloudSqlSqlServerMergePatch';
import {
    DatasetOptionsGcpGcsCsvMergePatch,
    DatasetOptionsGcpGcsCsvMergePatchFromJSON,
    DatasetOptionsGcpGcsCsvMergePatchFromJSONTyped,
    DatasetOptionsGcpGcsCsvMergePatchToJSON,
} from './DatasetOptionsGcpGcsCsvMergePatch';
import {
    DatasetOptionsHostedCsvMergePatch,
    DatasetOptionsHostedCsvMergePatchFromJSON,
    DatasetOptionsHostedCsvMergePatchFromJSONTyped,
    DatasetOptionsHostedCsvMergePatchToJSON,
} from './DatasetOptionsHostedCsvMergePatch';
import {
    DatasetOptionsMysqlMergePatch,
    DatasetOptionsMysqlMergePatchFromJSON,
    DatasetOptionsMysqlMergePatchFromJSONTyped,
    DatasetOptionsMysqlMergePatchToJSON,
} from './DatasetOptionsMysqlMergePatch';
import {
    DatasetOptionsPostgresMergePatch,
    DatasetOptionsPostgresMergePatchFromJSON,
    DatasetOptionsPostgresMergePatchFromJSONTyped,
    DatasetOptionsPostgresMergePatchToJSON,
} from './DatasetOptionsPostgresMergePatch';
import {
    DatasetOptionsRedshiftMergePatch,
    DatasetOptionsRedshiftMergePatchFromJSON,
    DatasetOptionsRedshiftMergePatchFromJSONTyped,
    DatasetOptionsRedshiftMergePatchToJSON,
} from './DatasetOptionsRedshiftMergePatch';
import {
    DatasetOptionsS3CsvMergePatch,
    DatasetOptionsS3CsvMergePatchFromJSON,
    DatasetOptionsS3CsvMergePatchFromJSONTyped,
    DatasetOptionsS3CsvMergePatchToJSON,
} from './DatasetOptionsS3CsvMergePatch';
import {
    DatasetOptionsSnowflakeMergePatch,
    DatasetOptionsSnowflakeMergePatchFromJSON,
    DatasetOptionsSnowflakeMergePatchFromJSONTyped,
    DatasetOptionsSnowflakeMergePatchToJSON,
} from './DatasetOptionsSnowflakeMergePatch';
import {
    DatasetOptionsSqlServerMergePatch,
    DatasetOptionsSqlServerMergePatchFromJSON,
    DatasetOptionsSqlServerMergePatchFromJSONTyped,
    DatasetOptionsSqlServerMergePatchToJSON,
} from './DatasetOptionsSqlServerMergePatch';

/**
 * @type DatasetOptionsMergePatch
 * Dataset connection options
 * @export
 */
export type DatasetOptionsMergePatch = { type: 'aws_aurora_mysql' } & DatasetOptionsAwsAuroraMysqlMergePatch | { type: 'aws_aurora_postgres' } & DatasetOptionsAwsAuroraPostgresMergePatch | { type: 'aws_rds_mysql' } & DatasetOptionsAwsRdsMysqlMergePatch | { type: 'aws_rds_postgres' } & DatasetOptionsAwsRdsPostgresMergePatch | { type: 'aws_rds_sql_server' } & DatasetOptionsAwsRdsSqlServerMergePatch | { type: 'aws_redshift_serverless' } & DatasetOptionsAwsRedshiftServerlessMergePatch | { type: 'azure_sql_server' } & DatasetOptionsAzureSqlServerMergePatch | { type: 'bigquery' } & DatasetOptionsBigQueryMergePatch | { type: 'classic' } & DatasetOptionsClassicMergePatch | { type: 'gcp_cloud_sql_mysql' } & DatasetOptionsGcpCloudSqlMysqlMergePatch | { type: 'gcp_cloud_sql_postgres' } & DatasetOptionsGcpCloudSqlPostgresMergePatch | { type: 'gcp_cloud_sql_sql_server' } & DatasetOptionsGcpCloudSqlSqlServerMergePatch | { type: 'gcp_gcs_csv' } & DatasetOptionsGcpGcsCsvMergePatch | { type: 'hosted_csv' } & DatasetOptionsHostedCsvMergePatch | { type: 'mysql' } & DatasetOptionsMysqlMergePatch | { type: 'postgres' } & DatasetOptionsPostgresMergePatch | { type: 'redshift' } & DatasetOptionsRedshiftMergePatch | { type: 's3_csv' } & DatasetOptionsS3CsvMergePatch | { type: 'snowflake' } & DatasetOptionsSnowflakeMergePatch | { type: 'sql_server' } & DatasetOptionsSqlServerMergePatch;

export function DatasetOptionsMergePatchFromJSON(json: any): DatasetOptionsMergePatch {
    return DatasetOptionsMergePatchFromJSONTyped(json, false);
}

export function DatasetOptionsMergePatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetOptionsMergePatch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['type']) {
        case 'aws_aurora_mysql':
            return {...DatasetOptionsAwsAuroraMysqlMergePatchFromJSONTyped(json, true), type: 'aws_aurora_mysql'};
        case 'aws_aurora_postgres':
            return {...DatasetOptionsAwsAuroraPostgresMergePatchFromJSONTyped(json, true), type: 'aws_aurora_postgres'};
        case 'aws_rds_mysql':
            return {...DatasetOptionsAwsRdsMysqlMergePatchFromJSONTyped(json, true), type: 'aws_rds_mysql'};
        case 'aws_rds_postgres':
            return {...DatasetOptionsAwsRdsPostgresMergePatchFromJSONTyped(json, true), type: 'aws_rds_postgres'};
        case 'aws_rds_sql_server':
            return {...DatasetOptionsAwsRdsSqlServerMergePatchFromJSONTyped(json, true), type: 'aws_rds_sql_server'};
        case 'aws_redshift_serverless':
            return {...DatasetOptionsAwsRedshiftServerlessMergePatchFromJSONTyped(json, true), type: 'aws_redshift_serverless'};
        case 'azure_sql_server':
            return {...DatasetOptionsAzureSqlServerMergePatchFromJSONTyped(json, true), type: 'azure_sql_server'};
        case 'bigquery':
            return {...DatasetOptionsBigQueryMergePatchFromJSONTyped(json, true), type: 'bigquery'};
        case 'classic':
            return {...DatasetOptionsClassicMergePatchFromJSONTyped(json, true), type: 'classic'};
        case 'gcp_cloud_sql_mysql':
            return {...DatasetOptionsGcpCloudSqlMysqlMergePatchFromJSONTyped(json, true), type: 'gcp_cloud_sql_mysql'};
        case 'gcp_cloud_sql_postgres':
            return {...DatasetOptionsGcpCloudSqlPostgresMergePatchFromJSONTyped(json, true), type: 'gcp_cloud_sql_postgres'};
        case 'gcp_cloud_sql_sql_server':
            return {...DatasetOptionsGcpCloudSqlSqlServerMergePatchFromJSONTyped(json, true), type: 'gcp_cloud_sql_sql_server'};
        case 'gcp_gcs_csv':
            return {...DatasetOptionsGcpGcsCsvMergePatchFromJSONTyped(json, true), type: 'gcp_gcs_csv'};
        case 'hosted_csv':
            return {...DatasetOptionsHostedCsvMergePatchFromJSONTyped(json, true), type: 'hosted_csv'};
        case 'mysql':
            return {...DatasetOptionsMysqlMergePatchFromJSONTyped(json, true), type: 'mysql'};
        case 'postgres':
            return {...DatasetOptionsPostgresMergePatchFromJSONTyped(json, true), type: 'postgres'};
        case 'redshift':
            return {...DatasetOptionsRedshiftMergePatchFromJSONTyped(json, true), type: 'redshift'};
        case 's3_csv':
            return {...DatasetOptionsS3CsvMergePatchFromJSONTyped(json, true), type: 's3_csv'};
        case 'snowflake':
            return {...DatasetOptionsSnowflakeMergePatchFromJSONTyped(json, true), type: 'snowflake'};
        case 'sql_server':
            return {...DatasetOptionsSqlServerMergePatchFromJSONTyped(json, true), type: 'sql_server'};
        default:
            throw new Error(`No variant of DatasetOptionsMergePatch exists with 'type=${json['type']}'`);
    }
}

export function DatasetOptionsMergePatchToJSON(value?: DatasetOptionsMergePatch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['type']) {
        case 'aws_aurora_mysql':
            return DatasetOptionsAwsAuroraMysqlMergePatchToJSON(value);
        case 'aws_aurora_postgres':
            return DatasetOptionsAwsAuroraPostgresMergePatchToJSON(value);
        case 'aws_rds_mysql':
            return DatasetOptionsAwsRdsMysqlMergePatchToJSON(value);
        case 'aws_rds_postgres':
            return DatasetOptionsAwsRdsPostgresMergePatchToJSON(value);
        case 'aws_rds_sql_server':
            return DatasetOptionsAwsRdsSqlServerMergePatchToJSON(value);
        case 'aws_redshift_serverless':
            return DatasetOptionsAwsRedshiftServerlessMergePatchToJSON(value);
        case 'azure_sql_server':
            return DatasetOptionsAzureSqlServerMergePatchToJSON(value);
        case 'bigquery':
            return DatasetOptionsBigQueryMergePatchToJSON(value);
        case 'classic':
            return DatasetOptionsClassicMergePatchToJSON(value);
        case 'gcp_cloud_sql_mysql':
            return DatasetOptionsGcpCloudSqlMysqlMergePatchToJSON(value);
        case 'gcp_cloud_sql_postgres':
            return DatasetOptionsGcpCloudSqlPostgresMergePatchToJSON(value);
        case 'gcp_cloud_sql_sql_server':
            return DatasetOptionsGcpCloudSqlSqlServerMergePatchToJSON(value);
        case 'gcp_gcs_csv':
            return DatasetOptionsGcpGcsCsvMergePatchToJSON(value);
        case 'hosted_csv':
            return DatasetOptionsHostedCsvMergePatchToJSON(value);
        case 'mysql':
            return DatasetOptionsMysqlMergePatchToJSON(value);
        case 'postgres':
            return DatasetOptionsPostgresMergePatchToJSON(value);
        case 'redshift':
            return DatasetOptionsRedshiftMergePatchToJSON(value);
        case 's3_csv':
            return DatasetOptionsS3CsvMergePatchToJSON(value);
        case 'snowflake':
            return DatasetOptionsSnowflakeMergePatchToJSON(value);
        case 'sql_server':
            return DatasetOptionsSqlServerMergePatchToJSON(value);
        default:
            throw new Error(`No variant of DatasetOptionsMergePatch exists with 'type=${value['type']}'`);
    }
}

