/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) SDK makes it easy to predict customer behavior using a simple API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IdentitySetPost,
    IdentitySetPostFromJSON,
    IdentitySetPostFromJSONTyped,
    IdentitySetPostToJSON,
} from './IdentitySetPost';

/**
 * 
 * @export
 * @interface IdentitySetsPost
 */
export interface IdentitySetsPost {
    [key: string]: IdentitySetPost;
}

export function IdentitySetsPostFromJSON(json: any): IdentitySetsPost {
    return IdentitySetsPostFromJSONTyped(json, false);
}

export function IdentitySetsPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentitySetsPost {
    return json;
}

export function IdentitySetsPostToJSON(value?: IdentitySetsPost | null): any {
    return value;
}

