/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Invoice
 */
export interface Invoice {
    /**
     * The amount of the invoice.
     * @type {number}
     * @memberof Invoice
     */
    amount: number;
    /**
     * 
     * @type {Date}
     * @memberof Invoice
     */
    due_date: Date;
    /**
     * The date of the invoice
     * @type {Date}
     * @memberof Invoice
     */
    effective_date: Date;
    /**
     * Whether or not the invoice has been paid.
     * @type {boolean}
     * @memberof Invoice
     */
    paid: boolean;
}

export function InvoiceFromJSON(json: any): Invoice {
    return InvoiceFromJSONTyped(json, false);
}

export function InvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Invoice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'due_date': (new Date(json['due_date'])),
        'effective_date': (new Date(json['effective_date'])),
        'paid': json['paid'],
    };
}

export function InvoiceToJSON(value?: Invoice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'due_date': (value.due_date.toISOString().substr(0,10)),
        'effective_date': (value.effective_date.toISOString().substr(0,10)),
        'paid': value.paid,
    };
}

