/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The age distribution for a given label (positives, candidates, negatives).
 * @export
 * @interface OutcomeAnalysisBiasDataAgeDistributionDatum
 */
export interface OutcomeAnalysisBiasDataAgeDistributionDatum extends Array<object> {
}

export function OutcomeAnalysisBiasDataAgeDistributionDatumFromJSON(json: any): OutcomeAnalysisBiasDataAgeDistributionDatum {
    return OutcomeAnalysisBiasDataAgeDistributionDatumFromJSONTyped(json, false);
}

export function OutcomeAnalysisBiasDataAgeDistributionDatumFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutcomeAnalysisBiasDataAgeDistributionDatum {
    return json;
}

export function OutcomeAnalysisBiasDataAgeDistributionDatumToJSON(value?: OutcomeAnalysisBiasDataAgeDistributionDatum | null): any {
    return value;
}

