/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RecommenderAnalysisPerformanceMetaModel,
    RecommenderAnalysisPerformanceMetaModelFromJSON,
    RecommenderAnalysisPerformanceMetaModelFromJSONTyped,
    RecommenderAnalysisPerformanceMetaModelToJSON,
} from './RecommenderAnalysisPerformanceMetaModel';

/**
 * 
 * @export
 * @interface RecommenderAnalysisPerformance
 */
export interface RecommenderAnalysisPerformance {
    /**
     * 
     * @type {RecommenderAnalysisPerformanceMetaModel}
     * @memberof RecommenderAnalysisPerformance
     */
    meta_model: RecommenderAnalysisPerformanceMetaModel;
}

export function RecommenderAnalysisPerformanceFromJSON(json: any): RecommenderAnalysisPerformance {
    return RecommenderAnalysisPerformanceFromJSONTyped(json, false);
}

export function RecommenderAnalysisPerformanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecommenderAnalysisPerformance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'meta_model': RecommenderAnalysisPerformanceMetaModelFromJSON(json['meta_model']),
    };
}

export function RecommenderAnalysisPerformanceToJSON(value?: RecommenderAnalysisPerformance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'meta_model': RecommenderAnalysisPerformanceMetaModelToJSON(value.meta_model),
    };
}

