/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) SDK makes it easy to predict customer behavior using a simple API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StreamPropertyDetails
 */
export interface StreamPropertyDetails {
    /**
     * the column used to populate this property on the event stream
     * @type {string}
     * @memberof StreamPropertyDetails
     */
    column_name?: string;
    /**
     * the dataset the column comes from
     * @type {string}
     * @memberof StreamPropertyDetails
     */
    dataset_id?: string;
}

export function StreamPropertyDetailsFromJSON(json: any): StreamPropertyDetails {
    return StreamPropertyDetailsFromJSONTyped(json, false);
}

export function StreamPropertyDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreamPropertyDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'column_name': !exists(json, 'column_name') ? undefined : json['column_name'],
        'dataset_id': !exists(json, 'dataset_id') ? undefined : json['dataset_id'],
    };
}

export function StreamPropertyDetailsToJSON(value?: StreamPropertyDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'column_name': value.column_name,
        'dataset_id': value.dataset_id,
    };
}

