/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) SDK makes it easy to predict customer behavior using a simple API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StreamPropertyDetails,
    StreamPropertyDetailsFromJSON,
    StreamPropertyDetailsFromJSONTyped,
    StreamPropertyDetailsToJSON,
} from './StreamPropertyDetails';

/**
 * 
 * @export
 * @interface StreamProperties
 */
export interface StreamProperties {
    [key: string]: StreamPropertyDetails;
}

export function StreamPropertiesFromJSON(json: any): StreamProperties {
    return StreamPropertiesFromJSONTyped(json, false);
}

export function StreamPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreamProperties {
    return json;
}

export function StreamPropertiesToJSON(value?: StreamProperties | null): any {
    return value;
}

