/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StreamPropertyInputFromDatasets
 */
export interface StreamPropertyInputFromDatasets {
    /**
     * the column used to populate this property on the event stream
     * @type {string}
     * @memberof StreamPropertyInputFromDatasets
     */
    column_name: string;
    /**
     * the dataset the column comes from
     * @type {string}
     * @memberof StreamPropertyInputFromDatasets
     */
    dataset_id: string;
}

export function StreamPropertyInputFromDatasetsFromJSON(json: any): StreamPropertyInputFromDatasets {
    return StreamPropertyInputFromDatasetsFromJSONTyped(json, false);
}

export function StreamPropertyInputFromDatasetsFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreamPropertyInputFromDatasets {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'column_name': json['column_name'],
        'dataset_id': json['dataset_id'],
    };
}

export function StreamPropertyInputFromDatasetsToJSON(value?: StreamPropertyInputFromDatasets | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'column_name': value.column_name,
        'dataset_id': value.dataset_id,
    };
}

