/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (Parameters used to PATCH the `TargetOptionsLookupApi` type.)
 * 
 * Lookup API target options
 * @export
 * @interface TargetOptionsLookupApiMergePatch
 */
export interface TargetOptionsLookupApiMergePatch {
    /**
     * The type of connection
     * @type {string}
     * @memberof TargetOptionsLookupApiMergePatch
     */
    type: string;
}

export function TargetOptionsLookupApiMergePatchFromJSON(json: any): TargetOptionsLookupApiMergePatch {
    return TargetOptionsLookupApiMergePatchFromJSONTyped(json, false);
}

export function TargetOptionsLookupApiMergePatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): TargetOptionsLookupApiMergePatch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function TargetOptionsLookupApiMergePatchToJSON(value?: TargetOptionsLookupApiMergePatch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
    };
}

