/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * One of:
 *   * default: Faraday default referenced representation
 * 
 * If not specified `default` is used.
 * @export
 * @enum {string}
 */
export enum TargetTransformPresetReferenced {
    Default = 'default'
}

export function TargetTransformPresetReferencedFromJSON(json: any): TargetTransformPresetReferenced {
    return TargetTransformPresetReferencedFromJSONTyped(json, false);
}

export function TargetTransformPresetReferencedFromJSONTyped(json: any, ignoreDiscriminator: boolean): TargetTransformPresetReferenced {
    return json as TargetTransformPresetReferenced;
}

export function TargetTransformPresetReferencedToJSON(value?: TargetTransformPresetReferenced | null): any {
    return value as any;
}

