/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (Parameters used to PUT a value of the `TargetOptionsSalesforceMarketingCloud` type.)
 * 
 * Salesforce Marketing Cloud target options
 * @export
 * @interface TargetOptionsSalesforceMarketingCloudPut
 */
export interface TargetOptionsSalesforceMarketingCloudPut {
    /**
     * Subdomain of the API Integration within your installed package in SFMC. Refer to <a href="https://hightouch.com/docs/destinations/sfmc#create-server-to-server-package">the HighTouch docs</a>.
     * @type {string}
     * @memberof TargetOptionsSalesforceMarketingCloudPut
     */
    api_subdomain: string;
    /**
     * Private SSH key of the FTP user created in SFMC. Refer to <a href="https://hightouch.com/docs/destinations/sfmc#create-ftp-user">the HighTouch docs</a>.
     * @type {string}
     * @memberof TargetOptionsSalesforceMarketingCloudPut
     */
    ftp_private_key?: string;
    /**
     * Password of the FTP user created in SFMC. Refer to <a href="https://hightouch.com/docs/destinations/sfmc#create-ftp-user">the HighTouch docs</a>.
     * @type {string}
     * @memberof TargetOptionsSalesforceMarketingCloudPut
     */
    ftp_user_password?: string;
    /**
     * Username of the FTP user created in SFMC. Typically a numeric Marketing Cloud MID. Refer to <a href="https://hightouch.com/docs/destinations/sfmc#create-ftp-user">the HighTouch docs</a>.
     * @type {string}
     * @memberof TargetOptionsSalesforceMarketingCloudPut
     */
    ftp_username?: string;
    /**
     * The type of connection
     * @type {string}
     * @memberof TargetOptionsSalesforceMarketingCloudPut
     */
    type: string;
}

export function TargetOptionsSalesforceMarketingCloudPutFromJSON(json: any): TargetOptionsSalesforceMarketingCloudPut {
    return TargetOptionsSalesforceMarketingCloudPutFromJSONTyped(json, false);
}

export function TargetOptionsSalesforceMarketingCloudPutFromJSONTyped(json: any, ignoreDiscriminator: boolean): TargetOptionsSalesforceMarketingCloudPut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'api_subdomain': json['api_subdomain'],
        'ftp_private_key': !exists(json, 'ftp_private_key') ? undefined : json['ftp_private_key'],
        'ftp_user_password': !exists(json, 'ftp_user_password') ? undefined : json['ftp_user_password'],
        'ftp_username': !exists(json, 'ftp_username') ? undefined : json['ftp_username'],
        'type': json['type'],
    };
}

export function TargetOptionsSalesforceMarketingCloudPutToJSON(value?: TargetOptionsSalesforceMarketingCloudPut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'api_subdomain': value.api_subdomain,
        'ftp_private_key': value.ftp_private_key,
        'ftp_user_password': value.ftp_user_password,
        'ftp_username': value.ftp_username,
        'type': value.type,
    };
}

