/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (Parameters used to POST a new value of the `TargetOptionsFacebookCustomAudiences` type.)
 * 
 * Facebook Custom Audiences target options
 * @export
 * @interface TargetOptionsFacebookCustomAudiencesPost
 */
export interface TargetOptionsFacebookCustomAudiencesPost {
    /**
     * The type of connection
     * @type {string}
     * @memberof TargetOptionsFacebookCustomAudiencesPost
     */
    type: string;
}

export function TargetOptionsFacebookCustomAudiencesPostFromJSON(json: any): TargetOptionsFacebookCustomAudiencesPost {
    return TargetOptionsFacebookCustomAudiencesPostFromJSONTyped(json, false);
}

export function TargetOptionsFacebookCustomAudiencesPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): TargetOptionsFacebookCustomAudiencesPost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function TargetOptionsFacebookCustomAudiencesPostToJSON(value?: TargetOptionsFacebookCustomAudiencesPost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
    };
}

