/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (Parameters used to PATCH the `TargetOptionsFacebookCustomAudiences` type.)
 * 
 * Facebook Custom Audiences target options
 * @export
 * @interface TargetOptionsFacebookCustomAudiencesMergePatch
 */
export interface TargetOptionsFacebookCustomAudiencesMergePatch {
    /**
     * The type of connection
     * @type {string}
     * @memberof TargetOptionsFacebookCustomAudiencesMergePatch
     */
    type: string;
}

export function TargetOptionsFacebookCustomAudiencesMergePatchFromJSON(json: any): TargetOptionsFacebookCustomAudiencesMergePatch {
    return TargetOptionsFacebookCustomAudiencesMergePatchFromJSONTyped(json, false);
}

export function TargetOptionsFacebookCustomAudiencesMergePatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): TargetOptionsFacebookCustomAudiencesMergePatch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function TargetOptionsFacebookCustomAudiencesMergePatchToJSON(value?: TargetOptionsFacebookCustomAudiencesMergePatch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
    };
}

