/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * CSV target options
 * @export
 * @interface TargetOptionsHostedCsv
 */
export interface TargetOptionsHostedCsv {
    /**
     * CSV delimiter
     * @type {string}
     * @memberof TargetOptionsHostedCsv
     */
    delimiter?: string;
    /**
     * Whether files are gzipped.
     * @type {boolean}
     * @memberof TargetOptionsHostedCsv
     */
    gzip?: boolean;
    /**
     * The Faraday-hosted URL of the target's csv output file.
     * @type {string}
     * @memberof TargetOptionsHostedCsv
     */
    output_url?: string;
    /**
     * Whether to always quote all fields, even if they don't require it. Some systems require this.
     * @type {boolean}
     * @memberof TargetOptionsHostedCsv
     */
    quote_all?: boolean;
    /**
     * The type of connection
     * @type {string}
     * @memberof TargetOptionsHostedCsv
     */
    type: string;
}

export function TargetOptionsHostedCsvFromJSON(json: any): TargetOptionsHostedCsv {
    return TargetOptionsHostedCsvFromJSONTyped(json, false);
}

export function TargetOptionsHostedCsvFromJSONTyped(json: any, ignoreDiscriminator: boolean): TargetOptionsHostedCsv {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'delimiter': !exists(json, 'delimiter') ? undefined : json['delimiter'],
        'gzip': !exists(json, 'gzip') ? undefined : json['gzip'],
        'output_url': !exists(json, 'output_url') ? undefined : json['output_url'],
        'quote_all': !exists(json, 'quote_all') ? undefined : json['quote_all'],
        'type': json['type'],
    };
}

export function TargetOptionsHostedCsvToJSON(value?: TargetOptionsHostedCsv | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'delimiter': value.delimiter,
        'gzip': value.gzip,
        'output_url': value.output_url,
        'quote_all': value.quote_all,
        'type': value.type,
    };
}

