/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) SDK makes it easy to predict customer behavior using a simple API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (Parameters used to POST a new value of the `TargetOptionsRedshift` type.)
 * 
 * AWS Redshift target options
 * @export
 * @interface TargetOptionsRedshiftPost
 */
export interface TargetOptionsRedshiftPost {
    /**
     * Table name
     * @type {string}
     * @memberof TargetOptionsRedshiftPost
     */
    table_name: string;
    /**
     * The type of connection
     * @type {string}
     * @memberof TargetOptionsRedshiftPost
     */
    type: string;
}

export function TargetOptionsRedshiftPostFromJSON(json: any): TargetOptionsRedshiftPost {
    return TargetOptionsRedshiftPostFromJSONTyped(json, false);
}

export function TargetOptionsRedshiftPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): TargetOptionsRedshiftPost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'table_name': json['table_name'],
        'type': json['type'],
    };
}

export function TargetOptionsRedshiftPostToJSON(value?: TargetOptionsRedshiftPost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'table_name': value.table_name,
        'type': value.type,
    };
}

