/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (Parameters used to PUT a value of the `TargetOptionsAwsAuroraPostgres` type.)
 * 
 * AWS Aurora Postgres target options
 * @export
 * @interface TargetOptionsAwsAuroraPostgresPut
 */
export interface TargetOptionsAwsAuroraPostgresPut {
    /**
     * Table name
     * @type {string}
     * @memberof TargetOptionsAwsAuroraPostgresPut
     */
    table_name: string;
    /**
     * The type of connection
     * @type {string}
     * @memberof TargetOptionsAwsAuroraPostgresPut
     */
    type: string;
}

export function TargetOptionsAwsAuroraPostgresPutFromJSON(json: any): TargetOptionsAwsAuroraPostgresPut {
    return TargetOptionsAwsAuroraPostgresPutFromJSONTyped(json, false);
}

export function TargetOptionsAwsAuroraPostgresPutFromJSONTyped(json: any, ignoreDiscriminator: boolean): TargetOptionsAwsAuroraPostgresPut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'table_name': json['table_name'],
        'type': json['type'],
    };
}

export function TargetOptionsAwsAuroraPostgresPutToJSON(value?: TargetOptionsAwsAuroraPostgresPut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'table_name': value.table_name,
        'type': value.type,
    };
}

