/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) SDK makes it easy to predict customer behavior using a simple API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (Parameters used to PUT a value of the `TargetOptionsS3Csv` type.)
 * 
 * CSV on Amazon S3 target options
 * @export
 * @interface TargetOptionsS3CsvPut
 */
export interface TargetOptionsS3CsvPut {
    /**
     * CSV delimiter
     * @type {string}
     * @memberof TargetOptionsS3CsvPut
     */
    delimiter?: string;
    /**
     * Whether to gzip files before uploading.
     * @type {boolean}
     * @memberof TargetOptionsS3CsvPut
     */
    gzip?: boolean;
    /**
     * The S3 object key inside of the bucket. For example, path/to/my/file.csv. If you enable gzip, best practice is to add .gz to the end. Note: strftime substitutions like %Y-%m-%d are supported.
     * @type {string}
     * @memberof TargetOptionsS3CsvPut
     */
    object_key: string;
    /**
     * Whether to always quote all fields, even if they don't require it. Some systems require this.
     * @type {boolean}
     * @memberof TargetOptionsS3CsvPut
     */
    quote_all?: boolean;
    /**
     * The type of connection
     * @type {string}
     * @memberof TargetOptionsS3CsvPut
     */
    type: string;
}

export function TargetOptionsS3CsvPutFromJSON(json: any): TargetOptionsS3CsvPut {
    return TargetOptionsS3CsvPutFromJSONTyped(json, false);
}

export function TargetOptionsS3CsvPutFromJSONTyped(json: any, ignoreDiscriminator: boolean): TargetOptionsS3CsvPut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'delimiter': !exists(json, 'delimiter') ? undefined : json['delimiter'],
        'gzip': !exists(json, 'gzip') ? undefined : json['gzip'],
        'object_key': json['object_key'],
        'quote_all': !exists(json, 'quote_all') ? undefined : json['quote_all'],
        'type': json['type'],
    };
}

export function TargetOptionsS3CsvPutToJSON(value?: TargetOptionsS3CsvPut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'delimiter': value.delimiter,
        'gzip': value.gzip,
        'object_key': value.object_key,
        'quote_all': value.quote_all,
        'type': value.type,
    };
}

