/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) SDK makes it easy to predict customer behavior using a simple API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (Parameters used to POST a new value of the `TargetOptionsSnowflake` type.)
 * 
 * Snowflake target options
 * @export
 * @interface TargetOptionsSnowflakePost
 */
export interface TargetOptionsSnowflakePost {
    /**
     * Database
     * @type {string}
     * @memberof TargetOptionsSnowflakePost
     */
    database: string;
    /**
     * Schema
     * @type {string}
     * @memberof TargetOptionsSnowflakePost
     */
    schema: string;
    /**
     * Table name
     * @type {string}
     * @memberof TargetOptionsSnowflakePost
     */
    table_name: string;
    /**
     * The type of connection
     * @type {string}
     * @memberof TargetOptionsSnowflakePost
     */
    type: string;
}

export function TargetOptionsSnowflakePostFromJSON(json: any): TargetOptionsSnowflakePost {
    return TargetOptionsSnowflakePostFromJSONTyped(json, false);
}

export function TargetOptionsSnowflakePostFromJSONTyped(json: any, ignoreDiscriminator: boolean): TargetOptionsSnowflakePost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'database': json['database'],
        'schema': json['schema'],
        'table_name': json['table_name'],
        'type': json['type'],
    };
}

export function TargetOptionsSnowflakePostToJSON(value?: TargetOptionsSnowflakePost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'database': value.database,
        'schema': value.schema,
        'table_name': value.table_name,
        'type': value.type,
    };
}

