/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) API makes it easy to predict customer behavior programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@faraday.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TraitStatisticalType,
    TraitStatisticalTypeFromJSON,
    TraitStatisticalTypeFromJSONTyped,
    TraitStatisticalTypeToJSON,
} from './TraitStatisticalType';

/**
 * (Parameters used to POST a new value of the `Trait` type.)
 * 
 * A fact about a person. 
 * 
 * The fact could be provided by Faraday, or alternatively could be defined by the client using data they have uploaded to Faraday.
 * 
 * These traits can be used by name in any of modeling, analysis, and reporting.
 * @export
 * @interface TraitPost
 */
export interface TraitPost {
    /**
     * Information about this field.
     * @type {string}
     * @memberof TraitPost
     */
    description?: string;
    /**
     * A more human-consumable version of the name of this field.
     * @type {string}
     * @memberof TraitPost
     */
    literate?: string;
    /**
     * A mapping of the input values used in modeling, to how they should be displayed in reports.
     * @type {object}
     * @memberof TraitPost
     */
    lookup_table?: object;
    /**
     * How to refer to this Trait in other API calls to Faraday.
     * @type {string}
     * @memberof TraitPost
     */
    name: string;
    /**
     * 
     * @type {TraitStatisticalType}
     * @memberof TraitPost
     */
    statistical_type?: TraitStatisticalType;
    /**
     * For numeric types, in what units is the data stored.
     * @type {string}
     * @memberof TraitPost
     */
    unit?: string;
}

export function TraitPostFromJSON(json: any): TraitPost {
    return TraitPostFromJSONTyped(json, false);
}

export function TraitPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraitPost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'literate': !exists(json, 'literate') ? undefined : json['literate'],
        'lookup_table': !exists(json, 'lookup_table') ? undefined : json['lookup_table'],
        'name': json['name'],
        'statistical_type': !exists(json, 'statistical_type') ? undefined : TraitStatisticalTypeFromJSON(json['statistical_type']),
        'unit': !exists(json, 'unit') ? undefined : json['unit'],
    };
}

export function TraitPostToJSON(value?: TraitPost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'literate': value.literate,
        'lookup_table': value.lookup_table,
        'name': value.name,
        'statistical_type': TraitStatisticalTypeToJSON(value.statistical_type),
        'unit': value.unit,
    };
}

