/* tslint:disable */
/* eslint-disable */
/**
 * Faraday REST API
 * The [Faraday](https://faraday.ai) SDK makes it easy to predict customer behavior using a simple API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (Parameters used to PUT a value of the `Trait` type.)
 * 
 * A fact about a person. 
 * 
 * The fact could be provided by Faraday, or alternatively could be defined by the client using data they have uploaded to Faraday.
 * 
 * These traits can be used by name in any of modeling, analysis, and reporting.
 * @export
 * @interface TraitPut
 */
export interface TraitPut {
    /**
     * statistical_type is an optional field which helps Faraday understand the nature of your data. 
     * For instance, when we know that a field has only a distinct set of values (e.g. it is categorical) we
     * can take steps to use that field more effectively in modeling, and we can provide more useful feedback when
     * reporting on its use. 
     * 
     * While this field is not required, it is recommended that you set it if possible.
     * @type {string}
     * @memberof TraitPut
     */
    statistical_type?: TraitPutStatisticalTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum TraitPutStatisticalTypeEnum {
    Categorical = 'categorical',
    Multicategorical = 'multicategorical',
    Ordinal = 'ordinal',
    Nominal = 'nominal'
}

export function TraitPutFromJSON(json: any): TraitPut {
    return TraitPutFromJSONTyped(json, false);
}

export function TraitPutFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraitPut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'statistical_type': !exists(json, 'statistical_type') ? undefined : json['statistical_type'],
    };
}

export function TraitPutToJSON(value?: TraitPut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'statistical_type': value.statistical_type,
    };
}

